# Generated by Django 5.0.1 on 2024-01-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexdata',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
